### ISSUE TITLE
Preview Mock Server samples always use http://jsapi.apiary.io/ as hostname

### ISSUE THREAD

**Issue by scullingworth** [apiaryio/apiary-client#103]
I set HOST: http://localhost at the top of my blueprint but it seems to be ignored in the sample code.  The host for the endpoint is set correctly at the top of the Example view, but it seems the host is ignored in all samples (cURL, PHP, Javascript) and is instead set to `http://jsapi.apiary.io/previews/null/reference/...`

Am I doing something wrong in my blueprint or is this a bug?  I'm using apiary cli version 0.3.2.

Thanks.

**Comment by miiila** [comment]
Hi Steve, 
thank you for reporting this issue. We've done some investigation and found a bug in application which is rendering examples.

Pull Requests is on it's way, so please give us some time to review it and merge. We will let you know once it is deployed.

Thank you for your patience.

Best regards,
Mila

**Comment by miiila** [comment]
Hi Steve,

I have deployed an update - could you please have a look and let me know if the issue is gone?

Thank you.

Best regards,
Mila

**Comment by scullingworth** [comment]
I did a `gem update` and ran `apiary preview` and looks like the update fixed the issue. The host in the sample CURL/javascript now matches the HOST value from the top of the blueprint. 

Thanks Mila!

**Comment by scullingworth** [comment]
Hi @miiila, it turns out that there is still an issue, specifically in the Console mode when invoking a call to the host.  When I click the "Call Resource" button, the host used is private-xxxx.apiary-proxy.com (instead of the host specified in the HOST value at the top of the blueprint.)  Could you please have a look?  Thanks.

**Comment by rcdilorenzo** [comment]
I'm also running into this problem and would love to know even a workaround to call from the generated preview.

**Comment by shwanton** [comment]
Still seeing this issue with `apiaryio 0.3.3`
Would love to use call the host api using the preview!

**Comment by Wideshanks** [comment]
Is the intention that the apiary blueprint `HOST` doesn't allow you to directly contact that host, but instead always proxies through `jsapi.apiary.io` (which seems to pull data from a URL like `http://private-a0a90-null.apiary-proxy.com/`).

So there's no way for us to use private server running on an internal IP via requests coming from the generated documentation?

**Comment by tu1ly** [comment]
the 'mock/proxy' has been removed from generated preview (we are not able to provide it now as it is dependant of blueprint stored in apiary)
![snap143](https://cloud.githubusercontent.com/assets/752248/17018828/e9963f16-4f39-11e6-8712-84cbff52ef23.png)

**Comment by jminkler** [comment]
It still tries to hit https://jsapi.apiary.io/apis/null/http-transactions/  though instead of replacing the project name where /null/ is ? 

Request URL:https://jsapi.apiary.io/apis/null/http-transactions/
Request Method:POST
Status Code:201 Created
Remote Address:23.23.128.123:443
